[book]
authors = []
language = "en"
multilingual = false
src = "src"

[output.html]
additional-css = ["theme/css/kroki.css"]
edit-url-template = "https://github.com/BA07-NINA/pam/edit/main/docs/{path}"
git-repository-url = "https://github.com/BA07-NINA/pam/"

[preprocessor.kroki-preprocessor]
