version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: nina_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: python_app
    environment:
      DATABASE_URL: "postgresql+psycopg2://your_user:your_password@postgres:5432/nina_database"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "app.py"]

volumes:
  postgres_data:
